grpc:
  host: order-service # 0.0.0.0
  port: 8001
  maxConnectionAge: 5m
  maxConnectionIdle: 5m
  time: 15s
  timeout: 15s

kafka:
  brokers:
    - "kafka-1:9094" # 127.0.0.1:9095
  topic: order_created
